export const AP = "ap"; // andra pradesh
export const AR = "ar"; // arunachal pradesh
export const AS = "as"; // assam
export const BR = "br"; // bihar
export const CH = "ch"; // chandigarh
export const DN = "dn"; // chhattisgarh
export const DD = "dd"; // dadra and nagar haveli
export const DL = "dl"; // daman and diu
export const GA = "ga"; // delhi
export const GJ = "gj"; // goa
export const HR = "hr"; // Gujarat
export const HP = "hp"; // himachal Pradesh
export const JK = "jk"; // jammu kashmir
export const JH = "jh"; // jharkhand
export const KA = "ka"; // karnatka
export const KL = "kl"; // kerla
export const LD = "ld"; // lakshadweep
export const MP = "mp"; // madhya pradesh
export const MH = "mh"; // maharastra
export const MN = "mn"; // manipur
export const ML = "ml"; // meghalaya
export const MZ = "mz"; // Mizoram
export const NL = "nl"; // nagaland
export const OR = "or"; // odisha
export const PY = "py"; // punducherry
export const PB = "pb"; // punjab
export const RJ = "rj"; // rajasthan
export const SK = "sk"; // sikkim
export const TN = "tn"; // tamil nadu
export const TG = "tg"; // telangana
export const TR = "tr"; // tripura
export const UP = "up"; // uttar presdesh
export const UT = "ut"; // Uttarakhand
export const WB = "wb"; // west bengal
